hydra:
  job:
    name: zero_shot_causal_lm
  run:
    dir: data/outputs/${hydra.job.name}
  sweep:
    dir: data/outputs/${hydra.job.name}/sweep_${now:%Y%m%d_%H%M%S}
    subdir: conf_${hydra.job.id}

debug: false
device: cuda
model: Qwen/Qwen2.5-7B-Instruct
batch_size: 1
